pipeline:
  build:
    image: ghcr.io/keval6b/xelatex:main
    commands:
      - make compile
  push:
    image: curlimages/curl
    commands:
      - curl --user "keval:$REGISTRY_TOKEN" -X "DELETE" "https://git.kapdee.uk/api/packages/keval/generic/cv/latest/keval-kapdee-cv.pdf"
      - curl --user "keval:$REGISTRY_TOKEN" --upload-file "keval-kapdee-cv.pdf" "https://git.kapdee.uk/api/packages/keval/generic/cv/latest/keval-kapdee-cv.pdf"
    secrets:
      - registry_token

branches: main
