pipeline:
  build:
    image: ghcr.io/keval6b/xelatex:main
    commands:
      - make compile
      - printenv
      - curl --user "keval:${registry_token}" --upload-file "keval-kapdee-cv.pdf" "https://git.kapdee.uk/api/packages/keval/generic/cv/latest/keval-kapdee-cv.pdf"
    secrets:
      - registry_token
    when:
      branch: main
