pipeline:
  build:
    image: ghcr.io/keval6b/xelatex:main
    commands:
      - make compile
  push:
    image: busybox
    commands:
      - curl --user "keval:$REGISTRY_TOKEN" --upload-file "keval-kapdee-cv.pdf" "https://git.kapdee.uk/api/packages/keval/generic/cv/$CI_BRANCH/keval-kapdee-cv.pdf"
    secrets:
      - registry_token
